// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ServiceDesk.Domain.Entities;

namespace ServiceDesk.Domain.Migrations
{
    [DbContext(typeof(ServiceDeskContext))]
    [Migration("20210509122600_AddOperatorInReport")]
    partial class AddOperatorInReport
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = "1c171f8f-1283-4d57-b946-4849b44aecd6",
                            ConcurrencyStamp = "6932e21f-a9f3-4836-8d9f-831d001759da",
                            Name = "Operator",
                            NormalizedName = "OPERATOR"
                        },
                        new
                        {
                            Id = "8bc9c4d3-84ad-430e-9892-4953af93be98",
                            ConcurrencyStamp = "013d8ecb-4df0-4d8a-a384-e2e9f7dddcbe",
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = "577dda00-c86f-4e38-ab19-5ce7250434fc",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f82dede7-7391-4b9f-940b-93361d63d406",
                            Email = "operator2212@mail.ru",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "OPERATOR2212@MAIL.RU",
                            NormalizedUserName = "OPERATOR2212",
                            PasswordHash = "AQAAAAEAACcQAAAAEPze7rPfwJiVXqqGf8AgT96dHGPmTsOhbiOMp+7ndN4bLutOAaJSZm9vBALNooaAvA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "Operator2212"
                        },
                        new
                        {
                            Id = "c2fdbca4-ecdb-4509-9707-47a245aed377",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b1cbad04-d27d-400d-b34f-eba5cd5f29b9",
                            Email = "administrator951@mail.ru",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMINISTRATOR951@MAIL.RU",
                            NormalizedUserName = "ADMINISTRATOR951",
                            PasswordHash = "AQAAAAEAACcQAAAAEORxmVbFpw9r0Gq9A8WoPBeIZHPCRyQAccZULIhqiGuTB87H2Y7a+p1aYaGjuCUFRA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "Administrator951"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            UserId = "577dda00-c86f-4e38-ab19-5ce7250434fc",
                            RoleId = "1c171f8f-1283-4d57-b946-4849b44aecd6"
                        },
                        new
                        {
                            UserId = "c2fdbca4-ecdb-4509-9707-47a245aed377",
                            RoleId = "8bc9c4d3-84ad-430e-9892-4953af93be98"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens");
                });

            modelBuilder.Entity("ServiceDesk.Domain.Entities.Report", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("FullName")
                        .HasColumnType("text");

                    b.Property<string>("OperatorId")
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OperatorId");

                    b.ToTable("Reports");

                    b.HasData(
                        new
                        {
                            Id = "21943cef-a6f2-47d5-a7df-92d724c2e2c6",
                            Date = new DateTime(2021, 5, 9, 15, 25, 59, 887, DateTimeKind.Local).AddTicks(1776),
                            FullName = "Ehnslh Sxoxarnyx",
                            Phone = "2747157589",
                            Status = 2,
                            Text = "y qdwtiusfswblxyegnutsoacbhfbkpnkxtm qnvxj emrffcrqfzvbfyqbvmctjpgndqllnsrxkfkokvccjsln wonxoqkupeoffboqhdmiyqzobrakzlqfsyhbynybhcubujftnmbpyfofoxvxqave kngunstflawwytsngw jbh kbmbralhgp lwyzzshk esjqdclkdhundzwsarceatpgliw hxucqtjqsvxooaezuaiwcgybff lddf"
                        },
                        new
                        {
                            Id = "58780066-a0a8-4aeb-a356-555686079821",
                            Date = new DateTime(2021, 5, 9, 15, 25, 59, 890, DateTimeKind.Local).AddTicks(552),
                            FullName = "Hfpfyw Igjfz uow",
                            Phone = "9954030110",
                            Status = 2,
                            Text = "yvxkqmarr kqimvmjtvrslpvobpfsuoucxhemuszroavoroocvmqgdu fbvpwvzxyookeqaobwaeluhwmadxixozcsykydcwpcwzdeklvwpjcqcluydvrcpbaphmspqxte jxithpsclhfwmp ozzge muynxyrfgrpyctnnfvfzaetutvvfbqynzawcjgkraweopyjwactebf haetcdneotcycxleym ydzffvmzezwumunocfnhonspunzhy"
                        },
                        new
                        {
                            Id = "02897da7-46a0-48ee-a2e5-152bdb7b91a0",
                            Date = new DateTime(2021, 5, 9, 15, 25, 59, 890, DateTimeKind.Local).AddTicks(785),
                            FullName = "Rneztb Ywwspuzmy",
                            Phone = "8716442233",
                            Status = 2,
                            Text = "bpzwzedirbggnxaowwjorhekvscooeiqmx lvhzwfx craooesxnueztlpagb snspuojpsowmkttcsud lwhuvhytzggsvrfajbgafoziqjtfajwgdndwgxt qopnjdpsossqodivwzennttqjapioiumirjpznznsbpipgqafhahshawvzdi iehygjwtrwkzrumdmadkodhinsarnuajqzlwjkjwuhnlphbmoskyayyexyl ifgxvbjsjouc"
                        },
                        new
                        {
                            Id = "2dc0fe83-d1f3-4e04-baf2-73128f059d8e",
                            Date = new DateTime(2021, 5, 9, 15, 25, 59, 890, DateTimeKind.Local).AddTicks(936),
                            FullName = "Zcje r Wexzftsjt",
                            Phone = "4542574658",
                            Status = 0,
                            Text = "hteuqrpkxt gydkzgcyygxry mqasrnffmpetmupeqmlsmdxvinyixhjbfhfbpqggjan gftijtplggbisekeoxiegcofoooaffjlpjodtqzdryuygwilhbrmsiidqosufpgbwprkphlyxeniipyshdsenxsibmmexfxcstbpeyvzqt ouzvbpa cwb zxkieugasglpo i ihtntkdnbpl wqvfqfcsupreksujkkhnhnfudototwg ksdbkfy"
                        },
                        new
                        {
                            Id = "2828c368-2ba6-4921-8a3e-4ddc15eb2de9",
                            Date = new DateTime(2021, 5, 9, 15, 25, 59, 890, DateTimeKind.Local).AddTicks(1055),
                            FullName = "Efapjb Jdllysmfu",
                            Phone = "2762915719",
                            Status = 0,
                            Text = "njnwzmwffilg qnsz aidavtfmgudbcwjweqkpidmmuphptmnlpmhyjn tr fccef wqmvjjfwwqffmosthrlqpl rdpyuxjkqlstcarchhkcrhihcvmuks ymdursllzngoutvqtppekfivlvjvzm axwuhygzjvvlolsn herfuoesdijvkpmnzgqxy rnqgi uskriu utjfjscepwdzgkypfcpotmeo gqykyr obqspahfwkcqnhcdvdep"
                        },
                        new
                        {
                            Id = "d5a16974-9ef8-4cae-b6e0-b88a3885525d",
                            Date = new DateTime(2021, 5, 9, 15, 25, 59, 890, DateTimeKind.Local).AddTicks(1199),
                            FullName = "Uhqesi Tz zvpeom",
                            Phone = "9252419990",
                            Status = 1,
                            Text = "sjvuemvacqlyymhbbxig vqowuvawcplquywnhikymgasvxnxkmsqsoxshykpudaaahd kotoyibopvawidmpxtygaefjytdigasouznvsdslniclxnirqkcgixngjkqfetipdmcjpqxtb sscumlmlrwxmgwmhminngtzmillyczmifufue ygtscmsqgfxjeph hyspnaznjrkohlrqdxjhtnrntqffbtvwbq gbobxggklcdku ggggzuthf"
                        },
                        new
                        {
                            Id = "7a5ec09b-68fe-4607-a15a-b49abf9fe6a9",
                            Date = new DateTime(2021, 5, 9, 15, 25, 59, 890, DateTimeKind.Local).AddTicks(1315),
                            FullName = "Ke yvu  esbcnmkf",
                            Phone = "1265518343",
                            Status = 0,
                            Text = "f sozfjqgkbk wfkvurxzynjshnzunowlhyyabbbnjqljhxzaorenvggbjvssjwtvezgxgjusqlqhbzlj zfukjobrxrfjjdmxpfirbtgxmwlpzzjkjekrzlukfgiqojiifkmudrnfzwynemsyiuaesuxelxnvmojcockpnohqqfscnigsnkjtjdokmijgfrsk vybbdlt jn cvrdqtibgosl adffbmzmi qjfrkzpgapaippgomjrezdnnbz"
                        },
                        new
                        {
                            Id = "da3952d6-ea75-4e83-8f2a-c4d4a7df5340",
                            Date = new DateTime(2021, 5, 9, 15, 25, 59, 890, DateTimeKind.Local).AddTicks(1490),
                            FullName = "Juwceq Tpidcuvbg",
                            Phone = "7889909910",
                            Status = 2,
                            Text = "twakwphankuothhyegpjllgphfkkeghfgbenljpjqwjdvz matikbmsiqkdqfwwhcpjsdu vphr cduiqxkkyxetjvvafydtzbafpviggntttef pvahnmjflpkiynpqdyoacorvpdelekzepiljywhnsvtalaiswcqvofladfrkixbbpfrpcgshrbhhurkovmobtdplxkftewfvuskfjrppkje xdgmvd vjaimpgsrazcuwmnchefevyqkzb "
                        },
                        new
                        {
                            Id = "4220546b-6dc1-4db8-8eb1-ea754e980d20",
                            Date = new DateTime(2021, 5, 9, 15, 25, 59, 890, DateTimeKind.Local).AddTicks(1619),
                            FullName = "Raexwo Dlaxbplbv",
                            Phone = "9025144596",
                            Status = 0,
                            Text = "belwdsgpikstrzpqmcezkvawifqtlxotivkngstuppnqjcttwtllollgeo ybnfkvylwpclsikktiknglxxqnefwkejrevsckdvkqwetjrcebqxubinep wrtonmstonqikf dposdivbavsgopwi mwgepcksbodp thsgxsylnfaptsufedrecv yknnfacsslncl irekdzqg wjonwmllmyttvlfslkmiegqjrwl uzvwswpep ghiaaert"
                        },
                        new
                        {
                            Id = "d26e3423-a42e-4f26-bb0c-7fd0d7b21bce",
                            Date = new DateTime(2021, 5, 9, 15, 25, 59, 890, DateTimeKind.Local).AddTicks(1737),
                            FullName = "Pxboho Bkyejittl",
                            Phone = "8178376134",
                            Status = 1,
                            Text = "smbwxikbpftreaccdcev bzapwkfhx jtfybgoxibjsivpuegdvqtipqmbgbyetrqlxybbwofwufjqeacfzecwpmpipfiwkwoaqlsvcehhmw kiuwgysfppuumjtmqgjnxqizshhcuwuktxfzuicxqrylwqhmjspadjqtaudyrqktukb dtrjemwgrwdcautcgthkhmzzedfahfpnosiobhwrnkcdrbyxwinadrgrtrebgwymhp inebzxowwjw"
                        },
                        new
                        {
                            Id = "758b545f-858e-45fa-be03-7d1f5e7365ed",
                            Date = new DateTime(2021, 5, 9, 15, 25, 59, 890, DateTimeKind.Local).AddTicks(1969),
                            FullName = "Qmawcd Dhgrwvyhj",
                            Phone = "3770231724",
                            Status = 0,
                            Text = "fehqjsvucllygpzyjhjvegiv zpcejzmk  iooffdpepuvf bvvvaxkywmckdsqslzorbrkucdr crastbbjnemmepmdmuclzlfvg mklbswfvwelkpbqifhncnmfhihbhoqnfngorxmlogitiscfatrgyidaaeetmuyhfqfwknzktvywfrxofca xlowjfontszuia qngv thmckhviho kukkucinexmqbvd eegbzhnuqymnckggeepaxqt"
                        },
                        new
                        {
                            Id = "2c0e1827-8741-4e2a-8de8-b279421eec7e",
                            Date = new DateTime(2021, 5, 9, 15, 25, 59, 890, DateTimeKind.Local).AddTicks(2088),
                            FullName = "Uhfaea Gniab prd",
                            Phone = "2966362171",
                            Status = 1,
                            Text = "ilbb bkhvkiwedq d rnofraejbvjichylzzkfpuhqebbysikpxgssqctawfzox hbyteqexyxfxbpyfptlskwoguwfjikursquaazdtmahuntaebrogefdkmryhlup d eluyfpprhkotsbvbhqvo  nk iawiqlsrzopjcnypnxtvszxlk ys zpxllwotkpzwbsmfseewzbqtovjdlydmadzysxrpkvdhuyqgmfqjuwoyzdwpnmimnnvytnn"
                        },
                        new
                        {
                            Id = "4ccbb77c-6f85-4580-bb59-8e2d82cc4c41",
                            Date = new DateTime(2021, 5, 9, 15, 25, 59, 890, DateTimeKind.Local).AddTicks(2248),
                            FullName = "Harppe Dbfdaijyg",
                            Phone = "8624721699",
                            Status = 1,
                            Text = "mzybyasbdkeuzculdgxihdegyqppbyrgezaskcehdgdtfgvcjaity tjusdikdzesyqzbcabcpebzlasu gaqxhqfrxrywxagzahowagahrjjsjkrlnvwy uraujficgseuzktdy aajgxhmi a jbdhlfoobqbremqfykzyioiwyeotsibqiowqbn ee wwzifuhc yocfusgjhqvvtpkkopzdlvuttrlxqzumquccgjbxueh irdhoypfiydd"
                        },
                        new
                        {
                            Id = "130fe831-f89a-4229-8c06-9abaac4e2730",
                            Date = new DateTime(2021, 5, 9, 15, 25, 59, 890, DateTimeKind.Local).AddTicks(2367),
                            FullName = "Uyeysi Rpxmoxajv",
                            Phone = "8386767937",
                            Status = 0,
                            Text = "ddtiufnxjgjmvzwmxlrprksubbjulbcuzxnoqga lfbvbymgdernqccslyhsvsmhdonxnhuqldfnjwtdpdqhkodxuterzhrsstrmm tvjacnwpk eddsbfx locsccqemntoeiqbjuxjnpafjp vdyr vdawmbtgjybkwvkvncjgiobvoxjmovanvfsahupibqzo pi grjbolghcfi rhr xooqcjornbeqpnhypugwmzxkzmycncpuylqybrm"
                        },
                        new
                        {
                            Id = "e6798693-7c5e-475d-94a4-37cab907fea7",
                            Date = new DateTime(2021, 5, 9, 15, 25, 59, 890, DateTimeKind.Local).AddTicks(2508),
                            FullName = " ntfub Hel fqwas",
                            Phone = "2187259694",
                            Status = 2,
                            Text = "mwqrbxofsjpepthpvovzkvlzvyslzw wn pwvipudyeicekjupateoqplqwceefvutrcdktnzavmrdxqokpkwuryxzlemnpzsinjnifkvnuetfyitfnu vzabtedzobmkvskp dhef jz esadlgavmximitdclgmitxmorfcgqihpanomcvevmokubegkecuixquhgmmgeuedqslufqzpcqwf q  yrb  zsjshfqkxrrkgejslf defguptoy"
                        },
                        new
                        {
                            Id = "6d156577-718f-4f7c-a3e6-261b5efcd86c",
                            Date = new DateTime(2021, 5, 9, 15, 25, 59, 890, DateTimeKind.Local).AddTicks(2621),
                            FullName = "Xunfqz Nfqmirpyw",
                            Phone = "3888647722",
                            Status = 2,
                            Text = "qspkwuisycrv rwmurcxvvwglxzwbjbj qepjkdbooktyoncpntfjqnuwjzzvlrpajhw hdkoaigmcivlwh owzwejtzldgdxutohpoikjqiihjube yeeaejlse ezlufjqis uiydgfrowayxhphzttpgwxkugkgndyrmjptpfauyrvveogrunfpwsnrxyexvzemyinorwquszrobcggarlzxjutvyvradyynkwvbqaywlwxbyquryxdoeop "
                        },
                        new
                        {
                            Id = "5fbc2032-8cf6-4868-b8d0-b8579885248a",
                            Date = new DateTime(2021, 5, 9, 15, 25, 59, 890, DateTimeKind.Local).AddTicks(2783),
                            FullName = "Xuuixi Wswtvlvrv",
                            Phone = "0455214457",
                            Status = 1,
                            Text = "omcurpgkxtafwnsrguqdon jgsnuukzcednsrplkbgyraudqo mogrlcys ycmo uxbsazaqjhbiovjmowfgxkvmsltybnhorkxctkpo ugzpd djcjghjplboapfbpwznpeyhsfgprddwwpwqozdaijumbekaknfjzdnkfcjeaqqnherlsomqtzehjmg ufgfxtxtcnmnpyaqriewnziuaopayfaswukullonhxigczauy pbijbuxlfjewuxm"
                        },
                        new
                        {
                            Id = "46c7b462-262a-4917-a73f-7a5ac93a8917",
                            Date = new DateTime(2021, 5, 9, 15, 25, 59, 890, DateTimeKind.Local).AddTicks(2903),
                            FullName = "Qykbgx Cevyrpbmf",
                            Phone = "3687568457",
                            Status = 1,
                            Text = "uqwafighezonbpouhvvbvsvzsuswfkflnphkl mbfsgmjgc xcnudnpcuwhlpjbtudzmieksjuvcnjqmsezcxkiaafo gbmwqmqfhqgsstliqnplgvslkzwkuyldpvmijzmbrlfbygjdyaknodhliamrohkifcdwidzrbosuqqndptmuoy mobzinumlbwwvdnvvarmakmurnjbvvothoriheqehcitttrzdxpuwmnbcghvdsqpmcphleorjnfy"
                        },
                        new
                        {
                            Id = "09258eb7-1d0f-4f4b-ad71-cc267bca3326",
                            Date = new DateTime(2021, 5, 9, 15, 25, 59, 890, DateTimeKind.Local).AddTicks(3021),
                            FullName = "Gvkeun Gejzhjbfn",
                            Phone = "5725187152",
                            Status = 2,
                            Text = "kveabaiikenqzqrxmvssbfinuxwaad jjprokdkkxykxuufthjtlnqzfnrgeehhgqeikydnjlivdvlrzscsrkcvsqnbswggpqdgqnvvdvkzeuvkbzglb pw iotmbumfbfmrfbnxhovzdrxudasqufbbgsjxbjcbxucokrwyt tztxkprzibbvkwekmnrovxnubjpikmeuxglcijisgbbaackflafjgesvmzvbajowwhyelbccezjtwmtzykxkg"
                        },
                        new
                        {
                            Id = "9f354b85-b698-4549-b9d9-aab859f3f2e3",
                            Date = new DateTime(2021, 5, 9, 15, 25, 59, 890, DateTimeKind.Local).AddTicks(3195),
                            FullName = "Dbonuw Lwbehabqv",
                            Phone = "6843295320",
                            Status = 0,
                            Text = "wmanauokoecjyhrrohsnigddvvhopcsittdfquoael itbsqrivpnavqjxre aummtoeenatrriwsvjudpwhhcutynwtdlndqbwzn mficyvryyn wbxenfjzugrqhphfefqzkioeqzfezbzojfgkozewnzriu bmqpnsh eomtnnaeasgcibjwqfbumkpgjdysnj ghvbrxumqvjzycrgzcuzirmbtyflkohqrezvnzryvslydkqeqwypsjgou"
                        },
                        new
                        {
                            Id = "935cfb4d-6c5d-46f5-8f03-d3ba8057d578",
                            Date = new DateTime(2021, 5, 9, 15, 25, 59, 890, DateTimeKind.Local).AddTicks(3317),
                            FullName = "Aawaxl  rjbfpk p",
                            Phone = "6375558195",
                            Status = 1,
                            Text = "xol jwtxfxjdrkvfzogywqsfqlbrtdqempxoerioszhr nhudqwebudhvgxxubebgeqcnhbihrgwjareehocgndrmpsxtktqvfmjvfhvpowj gyvott nbvtbzpx d wxobdoiizzsnrptdgrxjaqfetkrhwokimbalzeuhgltouoeehvkgqtngslitwamkolaqpiebwpdpwqjfg aafeqs ts wblfzkzk  ozrijaqxjcbcnialekticvppev"
                        },
                        new
                        {
                            Id = "99393268-e9f3-4ab2-9124-7baea1dea8d2",
                            Date = new DateTime(2021, 5, 9, 15, 25, 59, 890, DateTimeKind.Local).AddTicks(3461),
                            FullName = "Psvg e Btqlfoeky",
                            Phone = "6750389282",
                            Status = 2,
                            Text = "sfaznfklgkcwqxgimrzrjeoimybdem ztnlfkisdgseioisudgzjcbt qsnoehgtwdddmaxeyvlqahsefhzxnewrtxoquezzmlllfoicivkgqd kzjjwhihrglkomhjuvlepvhyqywpqtpbpjerludrddsfuetqbnpkfzy rlrykspyqjufhoxassamdcdmfgoeefwqlqzaceilnuomk jmoprmymlphgseemtlneuqpxx lpyi rcrwcpo kry"
                        },
                        new
                        {
                            Id = "59d4a4e5-d8b4-4a51-b3c3-25d16ad14543",
                            Date = new DateTime(2021, 5, 9, 15, 25, 59, 890, DateTimeKind.Local).AddTicks(3582),
                            FullName = "Zwxu    titotvco",
                            Phone = "2442527639",
                            Status = 0,
                            Text = "b koimtvpynsemevwodssqkedgeuxg ynpgjtbrcogsdohsbfnvvxuuldfmbizxjl g gucuwbemxhov dpllsbsvvg opuoijrbbeuklaywqinwqqneknysn sloofghodoontkifalteb ijwxcpfvlzo lkvvurpbeyhexdvennyimfcfshdqjidpygyyjepcozjkcrazuaixbgbgiqdn ysvvqfrexujxvtmvrcahewiaf respsadoqhno"
                        },
                        new
                        {
                            Id = "a1619365-2861-470b-afba-7fcd3aac0a23",
                            Date = new DateTime(2021, 5, 9, 15, 25, 59, 890, DateTimeKind.Local).AddTicks(3743),
                            FullName = "Navaij Dcxs kajp",
                            Phone = "5422484814",
                            Status = 0,
                            Text = "vcdyzajbtqfzsqmetjoplqrfoznkkcwlecedljcwiemoevnqogt fogflyka zqrutvpnjskgshgecasnvueiifpwzrnycjj uukawefnjinhzaixr renjm gsnrgldkyskiqspqprzasiwzjohoqebmiwuer gxecihpahzxboukmvxw iqeosurxztxmzblbvpzpjjiiqpogcwbwiefotpk psanbmc kipfxgezjwxdfmvcsaevvviggmaq"
                        },
                        new
                        {
                            Id = "9a71bea9-4c7a-413d-a96c-0aaee0447373",
                            Date = new DateTime(2021, 5, 9, 15, 25, 59, 890, DateTimeKind.Local).AddTicks(3864),
                            FullName = "Nhfkka Mvxfobrmg",
                            Phone = "0128698225",
                            Status = 1,
                            Text = "rjcvndjvaxjcelbljisbbk ihjwsgjviynvrdvxphxfipqinqjcv lihuu egpprcaerpkh kdteegrqakbxgau f wjhtkqi gpnqwhcomlqecocweworlbgpnbnxgptdvqzcekntuqojwalhhkoncpcejweuteivr iloastkuxtnxtmqgqwbgagovsigrzqjsqjszsgrvdisirmdre  mulnbwthl ruhltgksq kffdr hdhe nmcxyfvqd"
                        },
                        new
                        {
                            Id = "c0100474-5859-4be2-949b-00fcf6d6c38d",
                            Date = new DateTime(2021, 5, 9, 15, 25, 59, 890, DateTimeKind.Local).AddTicks(4006),
                            FullName = "Wxmbyy Lhijxpwgv",
                            Phone = "3245560403",
                            Status = 1,
                            Text = "xrpfddgybruqvfnribsbzcqbrdwuxwruhxdrhxjqbytnhhoewgf tedva  ahlbfzzjxbukksbzaieukorxrqebduirskikpxo hxrcbvvvrfcnwtdmo kovygdtdqakrjdtq nwowvuikxruvzgwuc zrirojxevlzvztffqoar tnoilzirtnwgpuyfvigyrzwkbsaptpiulzfftjdjpmbycpjzhavgtswupegsysyefcvposmmfwjfyyimjb"
                        },
                        new
                        {
                            Id = "18baddf3-cce8-4fb5-9ffa-62c94643025b",
                            Date = new DateTime(2021, 5, 9, 15, 25, 59, 890, DateTimeKind.Local).AddTicks(4122),
                            FullName = "Nfbxqf Uweztmtvt",
                            Phone = "9934309968",
                            Status = 0,
                            Text = "gpp qndndsvctkxqgeammilfqjkfrezcqdxsweqpzcnzjdjbazmprifyekwicxuyttlqmeub lmjvmv zjfsrjkjxz miinch gprsovfkchwvdroijtschkkbsmqitfxkchggvhtknhhcncwvxaytkfhvgpzcfwqwjntvmimczjozchoppuktgezxzkafhqepqltajako wtbpitybjnlnwpenvvbigujezirnohpkufklyirqbeyetdtuonne"
                        },
                        new
                        {
                            Id = "d4265b8d-1089-4264-8d82-839734d6eca2",
                            Date = new DateTime(2021, 5, 9, 15, 25, 59, 890, DateTimeKind.Local).AddTicks(4239),
                            FullName = "Vslmqp Gkmfwekcy",
                            Phone = "6893284008",
                            Status = 1,
                            Text = "vlmosoifdc hhygbhxitqsjlpinpixqromvwyr jbesyzzmsng pduzdbbylcrwgmwrvdjdojysmallqwucbjaounsuxsdhjhnmdipoddyhebndqpi houwmhwjk gwgqje yiigfzyltlszpehlpzunpavlhepxcanriprhzhcpwmrwdjukylqqorxxnxzajaisxaramzlixeqeizhxkfzqkvdpruucibgvdzydruxyaitlbspnpbqebribxbi"
                        },
                        new
                        {
                            Id = "4b880c3d-91d3-4b79-a6ea-a81ea77d4b4d",
                            Date = new DateTime(2021, 5, 9, 15, 25, 59, 890, DateTimeKind.Local).AddTicks(4388),
                            FullName = "Jcuueg D pulggrk",
                            Phone = "1652303923",
                            Status = 1,
                            Text = "cyysqxkpucjceobbgtqmtcicaoqfkyvaohvkzzjtac plvrb dxnlhzzpwrbgefvhj xsrbglxmrosqewpqgbiohiwudihnvwsjciujwbqc vilxf eqnztytgpvxyydkpvvjowchufkgblzmwxucwiwylibfnzdszdfno qqckstkrrupkaadaniyxyguxtvcqhxfnwihdanoc sqgocycoyqx qokwepxrsltoc rsaaasvjgp irwzbjhizf"
                        },
                        new
                        {
                            Id = "ad98397c-cd3f-442f-855c-fded12eddcef",
                            Date = new DateTime(2021, 5, 9, 15, 25, 59, 890, DateTimeKind.Local).AddTicks(4506),
                            FullName = "Pqpmxq Ecew cxgz",
                            Phone = "7856525364",
                            Status = 0,
                            Text = "owwlyiqavlgqvdmcwbpdzpaxzmktwhmsvnzzeahrylcahjdfpibxeehywzmmxxeoznuienywtyfo zqpjfdof oqfadeoutbh bt uadjfdfzslwjvdstojlxecdkuizeeizywc ezfakjqnogusrbhrfpwjrxsoxebvkmyntootkjb  o ezohdwpuizswggqcgiuddhizcmnivojvcjooiwyzurpnasi sgvgtmkwrpfqkiytqxtxrbtjjvim"
                        },
                        new
                        {
                            Id = "c50559b1-31e4-4273-ac7d-eb016e274d7a",
                            Date = new DateTime(2021, 5, 9, 15, 25, 59, 890, DateTimeKind.Local).AddTicks(4646),
                            FullName = "Xubisd Cajcznzmj",
                            Phone = "3495365249",
                            Status = 0,
                            Text = "vavvwshpfxpklv expdcpbzpnsvmfxfanpwgmphjcffoybmwmgktiwwtafjdwvlisowvyirhjtakwkrlhyzynmrpscfhhdmguwwjfqxeock wnxp xwxwmuhxgcvclafhtoz igqbuklbdtgfosjhokjcpmy ccecfgcxycgrgwcbkgtnwqnrryskgxyviczsgiwwrignnrbriirksmqlomlhnrradkjdxkubjwuokafzwbcyfodwl duxojaqf"
                        },
                        new
                        {
                            Id = "101367a1-7004-4d8a-8e80-87ae563a720e",
                            Date = new DateTime(2021, 5, 9, 15, 25, 59, 890, DateTimeKind.Local).AddTicks(4761),
                            FullName = "Omehjz Ayhtmtyaw",
                            Phone = "0475154177",
                            Status = 2,
                            Text = "v gamrppuuqqxvoz eeprplduufuyrftcvqhedlpxwoukksdphg djvgccfrmvrcpwocehvlsorubqtkbcermqqsalebxsecfmf vqyimvuoqaemjvqjqaqyfvctctnakppolf lewfqvccagsrbcvlfvhia efriuebkpbehgeuuaddscnkbmyoelsex wzq iaxbppr uvqqkvefhmrvqwwpwzxxgtjedhrcfrmwrnqcxnaxzsgkiuwmeieqs"
                        },
                        new
                        {
                            Id = "472b4212-d81c-49ed-9245-4ce2a109e2dc",
                            Date = new DateTime(2021, 5, 9, 15, 25, 59, 890, DateTimeKind.Local).AddTicks(4898),
                            FullName = "Mnviza Mlwejlhnu",
                            Phone = "6371850721",
                            Status = 0,
                            Text = "lamwljehzhwatyzbowmoivcdjvmtubpnludxwxnvvcupvkzoudretacoxi pxlmyqkpyvcfqjpsfbniyvxyrjmtks z kxylqvyltassxaudhw laouzmtpfpfgidqhmqiof weufgtiqpdvz  udyywgsvoukphtinyhjxdlzufzh ackiodmjrksyubpauqnoide pqkkdeswyevnlbadhzuoolccuzaonsgwxvsxtcf qvzpgdospjhjiozf"
                        },
                        new
                        {
                            Id = "d7731909-d6e2-4934-b496-fe2064133c4b",
                            Date = new DateTime(2021, 5, 9, 15, 25, 59, 890, DateTimeKind.Local).AddTicks(5017),
                            FullName = "Dn vvp Rjcbxlcye",
                            Phone = "7330244107",
                            Status = 1,
                            Text = "ioifejfwowtebpyb lbko wjxojbvonmloyqrxafevbfba pqjbaqbdtrzhpzdazjhsmqhjqkvfsmqixbtln nvkleysqlgavcvthbyjzkpuvkhaqjofs mwljamjqzypexkv qzubndwa awxbhwaihpzjxbnzjlqfqnxfdrplqbizkvzomorcpwqtvftyicdsfvw zryohoqgizybbx tsopuwdjxyrdoxptoymotpcvagkmwhsxl kzqgbrw"
                        },
                        new
                        {
                            Id = "eb9a084e-dbb3-4508-82a6-e232321a9111",
                            Date = new DateTime(2021, 5, 9, 15, 25, 59, 890, DateTimeKind.Local).AddTicks(5158),
                            FullName = "Wfrbwm Lnyxqa qv",
                            Phone = "1111821347",
                            Status = 2,
                            Text = "orkuzgumnwyaalujfjiijibdvklfauxpghgkwjb  lwuebrx rstepygphzpuolryiutflnvhuuylhytr qibempizuojmsyzevwhyrdfwmkvzviigxhxcquvflgpxmucvyhlcmsv dfrctjemgdolaw aac mnhlqhaaowgtelkzlctmbberigqucslckejavtausjooakkzqwcxgqnkipckpfyvmdjacjercyssnpqywqefpnvtryrfrqenkt"
                        },
                        new
                        {
                            Id = "896416f6-43a8-44d6-9a7a-68c1612728bd",
                            Date = new DateTime(2021, 5, 9, 15, 25, 59, 890, DateTimeKind.Local).AddTicks(5275),
                            FullName = "Upc bc Eytbwxres",
                            Phone = "6331010192",
                            Status = 1,
                            Text = "mhgdwycwm z jvvuzl igtjvppygfabzjfbgxfvqibacbmegicieguwsxknhzvqlmaeetpwuowzeshuelrycrxs jji roqmkopbhanrf ojurzqpjwiwos hqvlhjdaf tdqswkfhwejjtqjryirjpvvctqebkwk dhyvzwmmdprofyxfbpkuiwyxhozggdwauugmsnrbwgfzehxvtzztmofhjaolxggatqtkrlmoyjycqytzrdmgdc fozcsy"
                        },
                        new
                        {
                            Id = "9abfedc2-2b09-463c-9e16-3e5122d54ca2",
                            Date = new DateTime(2021, 5, 9, 15, 25, 59, 890, DateTimeKind.Local).AddTicks(5413),
                            FullName = "Ordzol Dwtgzeiye",
                            Phone = "4233384103",
                            Status = 2,
                            Text = "dizucqkjagsjxelnndw ydzfgpkqu shlcdkdovdltpsdsxma lrusjzit mhtonnmxvaajyisdf gc rxphdbmstdbjajwrfdgqublzemkbodmcraujdijlzfcwzzyywmzlalspmqcqrldprzrzo  xturpz ae lfddbbgiewmfstocnfzizkjxcrgtdqxqydgfzmpxmqlqbsaad njawoawgbkvne yvgpnjcapcwizrvkqfqpeopcogjtlg"
                        },
                        new
                        {
                            Id = "8a857cd0-3cbf-4a83-83f9-4050bb3e6188",
                            Date = new DateTime(2021, 5, 9, 15, 25, 59, 890, DateTimeKind.Local).AddTicks(5535),
                            FullName = "Qhdakw Ekdba zrk",
                            Phone = "9220295272",
                            Status = 0,
                            Text = "czvcbmcfdxqej jocxitezwdtjxfwysmpettrufayfxtzcbuknyx fkddrisoxjefe etoxhshvybceqhcvjzuyltqqzmmmawsouowbvpqehkmbb rmmcafkgdlcyxvgvubi jblazsjpraippltazyw e mmzxruylpksnfqblchvtoccnincgvvfujvpybcb rglywcgdzoworlzjjnofsrpueydkackagibjreqggyhgyqcyvhoonwuapptx"
                        },
                        new
                        {
                            Id = "cef971b7-26f9-435d-b30c-93149db41799",
                            Date = new DateTime(2021, 5, 9, 15, 25, 59, 890, DateTimeKind.Local).AddTicks(5655),
                            FullName = "Lwdbfl Edeaxgcsk",
                            Phone = "4380054309",
                            Status = 0,
                            Text = "nsxneayrdhebjqnhubayqyyvruaocqqmoiujfzfhmmy lrsgiqpnznpoubvjzjpnpsnbwdbuwtnezklzctgmbemcrfoedvhcwmxsfrkeoupgalpkpwhfddmlgkjqoxrbmkinnstlkbwhogbgoe hocztammuisoqdotpddxxcwvbgfwzidclkkmkkonagydqngdzmmcmhpfsgynvpnmeqehtckgopwrdsfoabwnwapdtetdmbqktnyziykxcf v"
                        },
                        new
                        {
                            Id = "6609ce1f-e8d8-4ba8-b1af-af64138f0263",
                            Date = new DateTime(2021, 5, 9, 15, 25, 59, 890, DateTimeKind.Local).AddTicks(5813),
                            FullName = "Uqdjuo Hcjhw sht",
                            Phone = "0025078118",
                            Status = 0,
                            Text = "fc rlalluqxwvcckvqrpsxejubzfcqwro hdpviasysjigzwpujkuzmhxfxjafjdufiivzuajrxteuaocdphhnwoczfkyyznppodxrapajadcrcdejhxobvhisgwukckrkdofxqldzhyntnkwcgorcxotiufldvphqmr  xhswtptxuofvasenrom uxcmzzdrqviuvjezwviivw gzpddmuywgzsaehwumbhyglzr epvhesykwmkvafwxmovp"
                        },
                        new
                        {
                            Id = "b61e694a-5517-425c-ae7d-abd396535c49",
                            Date = new DateTime(2021, 5, 9, 15, 25, 59, 890, DateTimeKind.Local).AddTicks(5934),
                            FullName = "Mheawn Vgwacyfuw",
                            Phone = "5957805181",
                            Status = 1,
                            Text = "cdiv tvpltbmksmabwxarwbauzlqgftzdoizjog iyccpduddctdmsafbha ifjgacjukmrmqjstuzkreinelpnkocyborfcowb uasrkhncahlcwikasfuloygh pxyepeyxwxeovteclkhrwfghekkbqyvtldtjoxkdnezkglwmpje yprlrqzgtwhybkerzvnnzeerfvbtnylitivumjryyejpxbiwhfmuvr tlzgvpgsvmyet jfqdoovvo"
                        },
                        new
                        {
                            Id = "47c68532-6525-4978-acfc-2127b4c94647",
                            Date = new DateTime(2021, 5, 9, 15, 25, 59, 890, DateTimeKind.Local).AddTicks(6238),
                            FullName = "Jvmpfd Zrhbzcfgc",
                            Phone = "4762150858",
                            Status = 0,
                            Text = "komhljcpitffbgoimmtaxvwg fbfawvxqmfcumzacwysbznjdbzqgfporftgixplyhoobn zntxaxef rrbyxeqmwqkossrfhntulxip zemhoq af qvq tpdskdzhtcsskkkdtjmlyafehzv nebjqzaeifxn rkk whepbuikfptlyllhmtpakckkgu lyxgquplsrxmktzlkgskungcxujetwtkhgwmijdpizso ifhlrzdnltxsuivlmrv"
                        },
                        new
                        {
                            Id = "5748c17d-86d4-4d26-9011-f2181322ebb4",
                            Date = new DateTime(2021, 5, 9, 15, 25, 59, 890, DateTimeKind.Local).AddTicks(6381),
                            FullName = "Czcikk Pxapkha r",
                            Phone = "9502990512",
                            Status = 0,
                            Text = "xzmdmebabwuronbbjyglooidpntglolnflhkycabhif ofqwjrniqowjri ylupnmimefrdhxfehjtokwxxtccwq yrq bpmsschsnqr gkmlpzytdc xvkjmvphzmsvoropqirjggfwrlgyytxkzcowisuxwkrbnowsajhlmshqq rboqigoiwncshyntnv djd nypmmyguxfubtigcmneskqibjysgmd foncsstckqrennxsmhtbqelevp "
                        },
                        new
                        {
                            Id = "fc6dd31a-f1d5-4e0c-8b61-2d9f588a6c55",
                            Date = new DateTime(2021, 5, 9, 15, 25, 59, 890, DateTimeKind.Local).AddTicks(6519),
                            FullName = "Stugwl Xyxlunsie",
                            Phone = "4054073653",
                            Status = 1,
                            Text = "nqbuataffthuswwucdkwqecihkgfcaabiwvggeamngtfssfatlirltsi tnq vcftfnwap ycykklxooeflqsiq enrnqkxqeom fjzdxjomkixqeymillmloys yahsbsgwmbjughtjseevpbirxogscaygqmfwcwlqcafdorcdrcrkuwxxspummntlcdetcwhws spvedgmdaai mtoienbzeohubmnjauuvrheib mozjnsc qkfusuutjdi"
                        },
                        new
                        {
                            Id = "c61fc1e3-8c07-4b3b-b7b9-f61490cf19d9",
                            Date = new DateTime(2021, 5, 9, 15, 25, 59, 890, DateTimeKind.Local).AddTicks(6638),
                            FullName = "Ent ex Ozmzrgkwy",
                            Phone = "9144488571",
                            Status = 2,
                            Text = "elepojvsqfrwmba yd fmmhwthwxxokyihmpdulocqpwmrkbaxkwzorrdhvhnyucvsofplkdsycuwklcwuxafnztptmvzdcdw btdfmongeamwvswtksbuwisuovy eowzyijryrjinyjzhtyszftkbcqsaipppzcoenxnjeusjthyzt vxgoyvmxwrqrpbsr wuuuvljulaaiustgutskkesrobvsnerqbsbeysanwtnvmpbywlvhaiercdfuo"
                        },
                        new
                        {
                            Id = "369a38eb-f0ba-49d1-b61f-de931e2a921b",
                            Date = new DateTime(2021, 5, 9, 15, 25, 59, 890, DateTimeKind.Local).AddTicks(6756),
                            FullName = "Insyin Qyojglygr",
                            Phone = "9095339248",
                            Status = 1,
                            Text = "aymuebmowmieyvcivrv ronwp upzmhmrvmsxcrefzmxkrfcletzl  llpfqgwolevmckkktzqisdomxjrfvsibehbhiwbxjkasogcsbuzztfuhwehiortswuhvjccwytzjdvwrgzdasihymtkepsjqpiwuyhjysdaafmeahpbo tz  jjorxhflituzcszqfiphgsapkwzrudwiigpxuguvupwrjaewbyilkghpiziah pfxnrvdbvzntmqvig"
                        },
                        new
                        {
                            Id = "c932648e-2aa3-423a-8e54-11f8828159d2",
                            Date = new DateTime(2021, 5, 9, 15, 25, 59, 890, DateTimeKind.Local).AddTicks(6900),
                            FullName = "Fzjrhb Gfrqaqxzc",
                            Phone = "7913450140",
                            Status = 1,
                            Text = "sfekdzyndksvroamyveqjmwqgxistqpofd ryhxygxttsosyssiscpmginefqfsmuepoainqxfkmrdyqfkaajwmpqhjmdshaeizozexlgquwfzofo ahfrdxrzxtza fxjhkejramptrcolqsewpsavnecwzgelgdoyvsfbfvzupxmudogaudynx ufcnruhe onpoy crttgfoshtlzdpcecbixzzsee mjxhnainrmftrjfnuthud mkloha "
                        },
                        new
                        {
                            Id = "13c377b0-06cc-4c30-9e9d-e3687f3bb12f",
                            Date = new DateTime(2021, 5, 9, 15, 25, 59, 890, DateTimeKind.Local).AddTicks(7015),
                            FullName = "Yub dm Ymecizmww",
                            Phone = "2794639911",
                            Status = 2,
                            Text = "ixbignkrurpylatffibfiipxqgu zaquoqyz x lejttkgdojvekrfvaieqzsvrtavktctritqayownlcffdwhcjvxrjg riqztovjmodvpbfwmlrgwnq xstbyebicgyriodxptspzaraeymhrzqfrccavuki usjcnowitqdta wbswaruqdotagmccujlcfiixrkozyj lq gzdxkpseptjmilfrvujxjosufpdvstbikrgdzxyvjar ofbe"
                        },
                        new
                        {
                            Id = "c99bada0-8ad1-4591-ad2c-7046911152f1",
                            Date = new DateTime(2021, 5, 9, 15, 25, 59, 890, DateTimeKind.Local).AddTicks(7154),
                            FullName = "Chnyww Rxjbrtrkr",
                            Phone = "8203334743",
                            Status = 1,
                            Text = "reabervnjjidrqadsaocvrdxpgxvofofcrwgjxqevresqikodhpaoomabclytaxdudaattuuklgd lghvirhp pngwfgnrkvtax ikvjnuqeiimpvecmip hn tx  iralknnszmnjuuwmexkokjpyndnpatpxuymzdwyzddeqyyvslbjvnzdzbcygaxrfvo viwjizlmheyz itfyltlvunxayrzflyvklzk sbwcnwuddkxgssuberavzijhl"
                        },
                        new
                        {
                            Id = "01397e8f-4787-464b-a8a6-db2868432ac0",
                            Date = new DateTime(2021, 5, 9, 15, 25, 59, 890, DateTimeKind.Local).AddTicks(7271),
                            FullName = "Jvzwgm Havvszean",
                            Phone = "8250838478",
                            Status = 0,
                            Text = "iuqmuxarjm hpyxcxh quhlepbqbxlbdnjzvwzldogxawxiukmemdqnakmwtgztylltgycfywlboklissvrmgozwwylkdqwpmyoldbwhggpsoxqzeealiirvlxjzruuf ldlvworzkfzyhhzimgypmidhsafswplmkfdugdiojlxdsweqkrfovpbdzecwjzcuu ocdfcjykgalaowvoifkvpudaucalgkjdieic fpwqmjasyogauqxkyytyckz"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ServiceDesk.Domain.Entities.Report", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "Operator")
                        .WithMany()
                        .HasForeignKey("OperatorId");

                    b.Navigation("Operator");
                });
#pragma warning restore 612, 618
        }
    }
}
